version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: codearena-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codearena
      MYSQL_USER: codearena_user
      MYSQL_PASSWORD: codearena_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - codearena-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codearena-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/codearena?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: codearena_user
      SPRING_DATASOURCE_PASSWORD: codearena_password
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_CLIENT_ID: ${FIREBASE_CLIENT_ID}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - codearena-network
    volumes:
      - ./backend:/app
      - /app/target

  # Judge Service
  judge:
    build:
      context: ./judge
      dockerfile: Dockerfile
    container_name: codearena-judge
    environment:
      BACKEND_URL: http://backend:8080
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: /app/firebase-key.json
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - codearena-network
    volumes:
      - ./judge:/app
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: codearena-frontend
    environment:
      VITE_API_URL: http://localhost:8080
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - codearena-network
    depends_on:
      - backend

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: codearena-redis
    ports:
      - "6379:6379"
    networks:
      - codearena-network
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

networks:
  codearena-network:
    driver: bridge 